# This file contains a sample Deployment, PodDisruptionBudget and a Service.
# The Deployment expect an image called `hub-portal-ui:dev`.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-apiportal-ui
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hub-apiportal-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hub-apiportal-ui
        app.kubernetes.io/component: api-portal-ui
        app.kubernetes.io/name: hub-apiportal-ui
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - hub-apiportal-ui
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      containers:
      - image: hub-portal-ui:dev
        name: hub-apiportal-ui
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - NET_RAW

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hub-apiportal-ui
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hub-apiportal-ui

---
apiVersion: v1
kind: Service
metadata:
  name: hub-apiportal-ui
  namespace: default
  labels:
    app.kubernetes.io/component: api-portal-ui
    app.kubernetes.io/name: hub-apiportal-ui
spec:
  ports:
  - name: web
    port: 80
    targetPort: 3000
  selector:
    app: hub-apiportal-ui
  type: ClusterIP